<a href="https://colab.research.google.com/github/gmdeorozco/Scikit-Learn-Library/blob/main/CalculateHypotenusa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn import linear_model

In [2]:
import numpy as np

In [29]:
catetos = np.array([[10,10],[8,8],[2,3],[1,1],[2,7],[5,10],[6,3],[12,5],[2,8]])
cuadrado_de_los_catetos = np.power(catetos,2)

In [30]:
cuadrado_de_los_catetos

array([[100, 100],
       [ 64,  64],
       [  4,   9],
       [  1,   1],
       [  4,  49],
       [ 25, 100],
       [ 36,   9],
       [144,  25],
       [  4,  64]])

In [31]:
np.add.reduce(cuadrado_de_los_catetos)

array([382, 421])

In [32]:
def internalsum( arr ):
  result = np.zeros(shape=(len(arr),1))
  index=0
  for cat in arr:
    result[index]=np.add.reduce(cat)
    index=index+1
  return result

suma_del_cuadrado_de_los_catetos = internalsum(cuadrado_de_los_catetos)
suma_del_cuadrado_de_los_catetos
    

array([[200.],
       [128.],
       [ 13.],
       [  2.],
       [ 53.],
       [125.],
       [ 45.],
       [169.],
       [ 68.]])

In [33]:
hipotenusa = np.sqrt(suma_del_cuadrado_de_los_catetos)
hipotenusa

array([[14.14213562],
       [11.3137085 ],
       [ 3.60555128],
       [ 1.41421356],
       [ 7.28010989],
       [11.18033989],
       [ 6.70820393],
       [13.        ],
       [ 8.24621125]])

In [34]:
reg = linear_model.LinearRegression()
reg.fit(catetos,hipotenusa)

LinearRegression()

In [35]:
reg.predict([[3,3]])

array([[4.60483954]])